BASE: ['resnet18_base.yaml']
DATA:
  BATCH_SIZE: 128
  DATASET: "medium_imagenet"
  IMG_SIZE: 96
  NUM_WORKERS: 32
  PIN_MEMORY: True
MODEL:
  NUM_CLASSES: 200
TRAIN:
  EPOCHS: 2
  WARMUP_EPOCHS: 1
  LR: 3e-3
  MIN_LR: 1e-3
  WARMUP_LR: 1e-3
  LR_SCHEDULER:
    NAME: "cosine"
  OPTIMIZER:
    NAME: "adamw"
    EPS: 1e-8
    BETAS: (0.9, 0.999)
    MOMENTUM: 0.9
OUTPUT: "output/resnet18_medium_imagenet"
SAVE_FREQ: 1
PRINT_FREQ: 500
